name: Check

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy

      - name: Check Formatting
        uses: actions-rust-lang/rustfmt@v1

      - name: Run Clippy
        run: cargo clippy

      - name: Run Tests
        run: cargo test